live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#686868"
blue = "#5CCFE6"
cyan = "#95E6CB"
green = "#A6CC70"
magenta = "#FFEE99"
red = "#F27983"
white = "#FFFFFF"
yellow = "#FFCC66"

[colors.normal]
black = "#191E2A"
blue = "#73D0FF"
cyan = "#95E6CB"
green = "#BAE67E"
magenta = "#FFD580"
red = "#FF3333"
white = "#C7C7C7"
yellow = "#FFA759"

[colors.primary]
background = "#202734"
foreground = "#CBCCC6"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
# Linux
size = 12.0
# MacOS
#size = 16.0

[font.normal]
# Linux
family = "monospace"
# MacOS
#family = "SF Mono"
style = "Regular"

# MacOS
# [[keyboard.bindings]]
# chars = "\u001Bb"
# key = "B"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001Bf"
# key = "F"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001Bd"
# key = "D"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001By"
# key = "Y"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001Br"
# key = "R"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001Bt"
# key = "T"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001B\u0019"
# key = "Y"
# mods = "Alt|Control"

# [[keyboard.bindings]]
# chars = "\u001B."
# key = "Period"
# mods = "Alt"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[window.dimensions]
# Linux
columns = 140
lines = 36
# MacOS
#columns = 100
#lines = 30

[window.padding]
x = 0
y = 0
