live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#686868"
blue = "#5CCFE6"
cyan = "#95E6CB"
green = "#A6CC70"
magenta = "#FFEE99"
red = "#F27983"
white = "#FFFFFF"
yellow = "#FFCC66"

[colors.normal]
black = "#191E2A"
blue = "#73D0FF"
cyan = "#95E6CB"
green = "#BAE67E"
magenta = "#FFD580"
red = "#FF3333"
white = "#C7C7C7"
yellow = "#FFA759"

[colors.primary]
background = "#202734"
foreground = "#CBCCC6"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0

[font.normal]
family = "monospace"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 50000

[window.dimensions]
columns = 140
lines = 36

[window.padding]
x = 0
y = 0
